apiVersion: apps/v1
kind: Deployment
metadata:
  name: paper-deployment
  labels:
    app: paper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paper
  template:
    metadata:
      labels:
        app: paper
    spec:
      volumes:
      - name: paper-pv-storage
        persistentVolumeClaim:
          claimName: paper-pv-claim
      containers:
      - name: paper-container
        image: gcr.io/eminent-century-263110/minecraftserver:v1
        ports:
        - containerPort: 25565
        volumeMounts:
        - mountPath: "/mnt/data"
          name: paper-pv-storage
